/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainerRouteImport } from './routes/trainer'
import { Route as RangesRouteImport } from './routes/ranges'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as BlackjackRouteImport } from './routes/blackjack'
import { Route as IndexRouteImport } from './routes/index'

const TrainerRoute = TrainerRouteImport.update({
  id: '/trainer',
  path: '/trainer',
  getParentRoute: () => rootRouteImport,
} as any)
const RangesRoute = RangesRouteImport.update({
  id: '/ranges',
  path: '/ranges',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const BlackjackRoute = BlackjackRouteImport.update({
  id: '/blackjack',
  path: '/blackjack',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blackjack': typeof BlackjackRoute
  '/coach': typeof CoachRoute
  '/learn': typeof LearnRoute
  '/quiz': typeof QuizRoute
  '/ranges': typeof RangesRoute
  '/trainer': typeof TrainerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blackjack': typeof BlackjackRoute
  '/coach': typeof CoachRoute
  '/learn': typeof LearnRoute
  '/quiz': typeof QuizRoute
  '/ranges': typeof RangesRoute
  '/trainer': typeof TrainerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blackjack': typeof BlackjackRoute
  '/coach': typeof CoachRoute
  '/learn': typeof LearnRoute
  '/quiz': typeof QuizRoute
  '/ranges': typeof RangesRoute
  '/trainer': typeof TrainerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/blackjack' | '/coach' | '/learn' | '/quiz' | '/ranges' | '/trainer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blackjack' | '/coach' | '/learn' | '/quiz' | '/ranges' | '/trainer'
  id:
    | '__root__'
    | '/'
    | '/blackjack'
    | '/coach'
    | '/learn'
    | '/quiz'
    | '/ranges'
    | '/trainer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlackjackRoute: typeof BlackjackRoute
  CoachRoute: typeof CoachRoute
  LearnRoute: typeof LearnRoute
  QuizRoute: typeof QuizRoute
  RangesRoute: typeof RangesRoute
  TrainerRoute: typeof TrainerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trainer': {
      id: '/trainer'
      path: '/trainer'
      fullPath: '/trainer'
      preLoaderRoute: typeof TrainerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranges': {
      id: '/ranges'
      path: '/ranges'
      fullPath: '/ranges'
      preLoaderRoute: typeof RangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blackjack': {
      id: '/blackjack'
      path: '/blackjack'
      fullPath: '/blackjack'
      preLoaderRoute: typeof BlackjackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlackjackRoute: BlackjackRoute,
  CoachRoute: CoachRoute,
  LearnRoute: LearnRoute,
  QuizRoute: QuizRoute,
  RangesRoute: RangesRoute,
  TrainerRoute: TrainerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
